---
apiVersion: v1
kind: List
items:
- apiVersion: operators.coreos.com/v1
  kind: OperatorSource
  metadata:
    name: enmasse-operators
    namespace: openshift-marketplace
  spec:
    type: appregistry
    endpoint: https://quay.io/cnr
    registryNamespace: enmasse
    displayName: "EnMasse Operators"
    publisher: "EnMasse"
- apiVersion: operators.coreos.com/v1
  kind: CatalogSourceConfig
  metadata:
    name: installed-enmasse-operators
    namespace: openshift-marketplace
  spec:
    csDisplayName: EnMasse Operators
    csPublisher: EnMasse
    packages: enmasse
    targetNamespace: openshift-operators
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: enmasse
    namespace: openshift-operators
  spec:
    channel: alpha
    name: enmasse
    source: installed-enmasse-operators
    sourceNamespace: openshift-operators